### ISSUE TITLE
Demo image chooser doesn't work except for the first data set (backdoor).

### ISSUE THREAD

**Issue by Baltoli** [WildPetScience/Triton#23]
```
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index: 5, Size: 1
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at uk.ac.cam.cl.wildpetscience.triton.pipeline.TestVideoChooser$1.mouseClicked(TestVideoChooser.java:35)
    at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
```

**Comment by w-shackleton** [comment]
Lol I only ever tested on the first one
